Alternate light colors. Try to catch ResourceAccessException
Added xmas2 light option where selected lights alternate between red and
green. Half are red, half are green and then they switch.

Threads are sometimes stopping due to:
 Exception in thread "xmas [18, 20]"
org.springframework.web.client.ResourceAccessException: I/O error on GET
request for "http://192.168.1.23/api/<username>/lights/18": Connection
timed out: connect; nested exception is java.net.ConnectException:
Connection timed out: connect

Added logic to catch the exception and retry up to 5 times before
killing the thread